const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Plugins.AJAX,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Internationalization,
		C3.Plugins.progressbar,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Internationalization.Acts.LoadFromJSON,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Internationalization.Acts.SetLocale,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Internationalization.Exps.Lookup,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.RemoveLayer,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.progressbar.Acts.Destroy,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{tx_1: 0},
	{tx_2: 0},
	{tx_3: 0},
	{Esmaecer: 0},
	{tx_4: 0},
	{tx_5: 0},
	{tx_6: 0},
	{tx_7: 0},
	{tx_8: 0},
	{tx_9: 0},
	{tx_10: 0},
	{tx_11: 0},
	{tx_12: 0},
	{tx_13: 0},
	{tx_14: 0},
	{tx_15: 0},
	{tx_16: 0},
	{tx_17: 0},
	{tx_18: 0},
	{tx_19: 0},
	{tx_20: 0},
	{tx_simples: 0},
	{tx_21: 0},
	{tx_22: 0},
	{tx_23: 0},
	{tx_24: 0},
	{tx_25: 0},
	{bt_brasil: 0},
	{bt_china: 0},
	{bt_entrar: 0},
	{bt_espanha: 0},
	{bt_italia: 0},
	{bt_usa: 0},
	{bt_concluir: 0},
	{bt_blue: 0},
	{bt_orange: 0},
	{Senóide: 0},
	{bt_home: 0},
	{bt_reiniciar: 0},
	{BT_OK: 0},
	{proximo: 0},
	{BT_OK2: 0},
	{BT_OK3: 0},
	{PSE_: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{intro_: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{código_produto: 0},
	{Sprite9: 0},
	{Sprite8: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Piscar: 0},
	{posicao: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{CHECK_IN_: 0},
	{CHECK_IN_2: 0},
	{config_tabela: 0},
	{config_tabela2: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{seta_down: 0},
	{seta_left: 0},
	{seta_right: 0},
	{seta_up: 0},
	{bg_1: 0},
	{bg_2: 0},
	{bg_3: 0},
	{bg_4: 0},
	{bg_5: 0},
	{bg_6: 0},
	{bg_clique: 0},
	{bg_solido_1: 0},
	{bg_7: 0},
	{bg_8: 0},
	{bg_9: 0},
	{bg_10: 0},
	{bg_clique2: 0},
	{bg_clique3: 0},
	{bg_clique4: 0},
	{bg_11: 0},
	{bg_12: 0},
	{bg_13: 0},
	{AJAX: 0},
	{EntradaDeTexto: 0},
	{Mouse: 0},
	{Teclado: 0},
	{tradutor: 0},
	{EntradaDeTexto2: 0},
	{EntradaDeTexto3: 0},
	{EntradaDeTexto4: 0},
	{BarraDeProgresso: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Navegador: 0},
	{bandeiras: 0},
	{IdiomaSelecionado: 0},
	{Controle: 0}
];

self.InstanceType = {
	tx_1: class extends self.ITextInstance {},
	tx_2: class extends self.ITextInstance {},
	tx_3: class extends self.ITextInstance {},
	tx_4: class extends self.ITextInstance {},
	tx_5: class extends self.ITextInstance {},
	tx_6: class extends self.ITextInstance {},
	tx_7: class extends self.ITextInstance {},
	tx_8: class extends self.ITextInstance {},
	tx_9: class extends self.ITextInstance {},
	tx_10: class extends self.ITextInstance {},
	tx_11: class extends self.ITextInstance {},
	tx_12: class extends self.ITextInstance {},
	tx_13: class extends self.ITextInstance {},
	tx_14: class extends self.ITextInstance {},
	tx_15: class extends self.ITextInstance {},
	tx_16: class extends self.ITextInstance {},
	tx_17: class extends self.ITextInstance {},
	tx_18: class extends self.ITextInstance {},
	tx_19: class extends self.ITextInstance {},
	tx_20: class extends self.ITextInstance {},
	tx_simples: class extends self.ITextInstance {},
	tx_21: class extends self.ITextInstance {},
	tx_22: class extends self.ITextInstance {},
	tx_23: class extends self.ITextInstance {},
	tx_24: class extends self.ITextInstance {},
	tx_25: class extends self.ITextInstance {},
	bt_brasil: class extends self.ISpriteInstance {},
	bt_china: class extends self.ISpriteInstance {},
	bt_entrar: class extends self.ISpriteInstance {},
	bt_espanha: class extends self.ISpriteInstance {},
	bt_italia: class extends self.ISpriteInstance {},
	bt_usa: class extends self.ISpriteInstance {},
	bt_concluir: class extends self.ISpriteInstance {},
	bt_blue: class extends self.ISpriteInstance {},
	bt_orange: class extends self.ISpriteInstance {},
	bt_home: class extends self.ISpriteInstance {},
	bt_reiniciar: class extends self.ISpriteInstance {},
	BT_OK: class extends self.ISpriteInstance {},
	proximo: class extends self.ISpriteInstance {},
	BT_OK2: class extends self.ISpriteInstance {},
	BT_OK3: class extends self.ISpriteInstance {},
	PSE_: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	intro_: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	código_produto: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	posicao: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	CHECK_IN_: class extends self.ISpriteInstance {},
	CHECK_IN_2: class extends self.ISpriteInstance {},
	config_tabela: class extends self.ISpriteInstance {},
	config_tabela2: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	seta_down: class extends self.ISpriteInstance {},
	seta_left: class extends self.ISpriteInstance {},
	seta_right: class extends self.ISpriteInstance {},
	seta_up: class extends self.ISpriteInstance {},
	bg_1: class extends self.ISpriteInstance {},
	bg_2: class extends self.ISpriteInstance {},
	bg_3: class extends self.ISpriteInstance {},
	bg_4: class extends self.ISpriteInstance {},
	bg_5: class extends self.ISpriteInstance {},
	bg_6: class extends self.ISpriteInstance {},
	bg_clique: class extends self.ISpriteInstance {},
	bg_solido_1: class extends self.ISpriteInstance {},
	bg_7: class extends self.ISpriteInstance {},
	bg_8: class extends self.ISpriteInstance {},
	bg_9: class extends self.ISpriteInstance {},
	bg_10: class extends self.ISpriteInstance {},
	bg_clique2: class extends self.ISpriteInstance {},
	bg_clique3: class extends self.ISpriteInstance {},
	bg_clique4: class extends self.ISpriteInstance {},
	bg_11: class extends self.ISpriteInstance {},
	bg_12: class extends self.ISpriteInstance {},
	bg_13: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	tradutor: class extends self.IInstance {},
	EntradaDeTexto2: class extends self.ITextInputInstance {},
	EntradaDeTexto3: class extends self.ITextInputInstance {},
	EntradaDeTexto4: class extends self.ITextInputInstance {},
	BarraDeProgresso: class extends self.IProgressBarInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	bandeiras: class extends self.ISpriteInstance {}
}